version: "2"

services:
  web:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - .:/var/www/html
     - ./conf/site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.0-fpm
    volumes:
      - .:/var/www/html

  db:
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
      MYSQL_DATABASE: test